const urlsToCache = [
  'games/alienhominid/alienhominid.html',
  'games/alienhominid/alienhominid.swf',
  'games/alienhominid/index.html'
  'games/bloonstd/bloonstd.html',
  'games/bloonstd/bloonstd.swf',
  'games/bloonstd/index.html'
  'games/bloxorz/bloxors.swf',
  'games/bloxorz/bloxorz.html',
  'games/bloxorz/index.html'
  'games/btd2/btd2.swf',
  'games/btd2/index.html'
  'games/btd3/btd3.swf',
  'games/btd3/index.html'
  'games/btd4/btd4.swf',
  'games/btd4/index.html'
  'games/diggy/diggy.html',
  'games/diggy/diggy.swf',
  'games/diggy/index.html'
  'games/ducklife/ducklife.html',
  'games/ducklife/ducklife.swf',
  'games/ducklife/index.html'
  'games/ducklife2/ducklife2.html',
  'games/ducklife2/ducklife2.swf',
  'games/ducklife2/index.html'
  'games/ducklife3/ducklife3.html',
  'games/ducklife3/ducklife3.swf',
  'games/ducklife3/index.html'
  'games/ducklife4/ducklife4.html',
  'games/ducklife4/ducklife4.swf',
  'games/ducklife4/index.html'
  'games/escapingtheprison/escapingtheprison.swf',
  'games/escapingtheprison/index.html'
  'games/fancypantsadventure/fancypantsadventure.swf',
  'games/fancypantsadventure/index.html'
  'games/fancypantsadventure2/fancy-pants-adventure2.swf',
  'games/fancypantsadventure2/index.html'
  'games/fancypantsadventure3/FPAWorld3.swf',
  'games/fancypantsadventure3/index.html'
  'games/fleeingthecomplex/5.swf',
  'games/fleeingthecomplex/index.html'
  'games/fnaf3/fnaf3.html',
  'games/fnaf3/fnaf3.swf',
  'games/fnaf3/index.html'
  'games/gunmayhem/gunmayhem.html',
  'games/gunmayhem/gunmayhem.swf',
  'games/gunmayhem/index.html'
  'games/gunmayhem2/gunmayhem2.html',
  'games/gunmayhem2/gunmayhem2.swf',
  'games/gunmayhem2/index.html'
  'games/gunmayhemredux/gunmayhemredux.html',
  'games/gunmayhemredux/gunmayhemredux.swf',
  'games/gunmayhemredux/index.html'
  'games/happywheels/HappyWheels.swf',
  'games/happywheels/index.html'
  'games/infiltratingtheairship/index.html',
  'games/infiltratingtheairship/infiltratingtheairship.swf'
  'games/learntofly/index.html',
  'games/learntofly/learntofly.html',
  'games/learntofly/learntofly.swf'
  'games/learntofly2/index.html',
  'games/learntofly2/learntofly2.html',
  'games/learntofly2/learntofly2.swf'
  'games/learntofly3/index.html',
  'games/learntofly3/learntofly3.html',
  'games/learntofly3/learntofly3.swf'
  'games/motox3m/index-old.html',
  'games/motox3m/index.html',
  'games/motox3m/motox3m.html',
  'games/motox3m/motox3m.min.js',
  'games/motox3m/motox3m.swf'
  'games/motox3m2/index.html',
  'games/motox3m2/motox3m2.html',
  'games/motox3m2/motox3m2.swf'
  'games/nyancat/index.html',
  'games/nyancat/nyancat.html',
  'games/nyancat/nyancat.swf'
  'games/papasbakeria/index.html',
  'games/papasbakeria/papasbakeria.swf'
  'games/papascheeseria/index.html',
  'games/papascheeseria/papascheeseria.swf'
  'games/papascupcakeria/index.html',
  'games/papascupcakeria/papascupcakeria.swf'
  'games/papasdonuteria/index.html',
  'games/papasdonuteria/papasdonuteria.swf'
  'games/papasfreezeria/index.html',
  'games/papasfreezeria/papasfreezeria.swf'
  'games/papaspancakeria/index.html',
  'games/papaspancakeria/papaspancakeria.swf'
  'games/papaspastaria/index.html',
  'games/papaspastaria/papaspastaria.swf'
  'games/papaspizzaria/c5c02c4e65c1c4423a97.wasm',
  'games/papaspizzaria/index.html',
  'games/papaspizzaria/papaspizzaria.jpg',
  'games/papaspizzaria/papaspizzaria.swf',
  'games/papaspizzaria/ruffle.js'
  'games/papasscooperia/index.html',
  'games/papasscooperia/papasscooperia.swf'
  'games/papassushiria/index.html',
  'games/papassushiria/papassushiria.swf'
  'games/papaswingeria/index.html',
  'games/papaswingeria/papaswingeria.swf'
  'games/picosschool/index.html',
  'games/picosschool/picosschool.html',
  'games/picosschool/picosschool.swf'
  'games/portalflash/index.html',
  'games/portalflash/portalflash.html',
  'games/portalflash/portalflash.swf'
  'games/raftwars/index.html',
  'games/raftwars/raftwars.html',
  'games/raftwars/raftwars.swf'
  'games/raftwars2/index.html',
  'games/raftwars2/raftwars2.html',
  'games/raftwars2/raftwars2.swf'
  'games/riddleschool/index.html',
  'games/riddleschool/riddleschool.html',
  'games/riddleschool/riddleschool.swf'
  'games/riddleschool2/index.html',
  'games/riddleschool2/riddleschool2.html',
  'games/riddleschool2/riddleschool2.swf'
  'games/riddleschool3/index.html',
  'games/riddleschool3/riddleschool3.html',
  'games/riddleschool3/riddleschool3.swf'
  'games/riddleschool4/index.html',
  'games/riddleschool4/riddleschool4.html',
  'games/riddleschool4/riddleschool4.swf'
  'games/riddleschool5/index.html',
  'games/riddleschool5/riddleschool5.html',
  'games/riddleschool5/riddleschool5.swf'
  'games/riddleschooltransfer/index.html',
  'games/riddleschooltransfer/riddleschooltransfer.html',
  'games/riddleschooltransfer/riddletransfer.swf'
  'games/riddleschooltransfer2/index.html',
  'games/riddleschooltransfer2/riddleschooltransfer2.html',
  'games/riddleschooltransfer2/riddletransfer2.swf'
  'games/run/index.html',
  'games/run/run.html',
  'games/run/run.swf'
  'games/run2/index.html',
  'games/run2/run2.html',
  'games/run2/run2.swf'
  'games/run3/index.html',
  'games/run3/run3.html',
  'games/run3/run3.swf'
  'games/solitaire/index.html',
  'games/solitaire/solitaire.swf'
  'games/stealingthediamond/index.html',
  'games/stealingthediamond/stealingthediamond.swf'
  'games/supermeatboy/index.html',
  'games/supermeatboy/supermeatboy.swf'
  'games/supersmashflash/index.html',
  'games/supersmashflash/supersmashflash.html',
  'games/supersmashflash/supersmashflash.swf'
  'games/thebindingofisaac/index.html',
  'games/thebindingofisaac/the_binding_of_isaac.swf'
  'games/theimpossiblequiz/index.html',
  'games/theimpossiblequiz/theimpossiblequiz.html',
  'games/theimpossiblequiz/theimpossiblequiz.swf'
  'games/theimpossiblequiz2/index.html',
  'games/theimpossiblequiz2/theimpossiblequiz2.html',
  'games/theimpossiblequiz2/theimpossiblequiz2.swf'
  'games/themehotel/index.html',
  'games/themehotel/themehotel.swf'
  'games/vex/index.html',
  'games/vex/vex.swf'
  'games/vex2/index.html',
  'games/vex2/vex2.swf'
  'games/worldshardestgame/index.html',
  'games/worldshardestgame/theworldshardestgame.swf',
  'games/worldshardestgame/whg.swf',
  'games/worldshardestgame/worldshardestgame.html'
  'games/worldshardestgame2/index.html',
  'games/worldshardestgame2/theworldshardestgame2.swf',
  'games/worldshardestgame2/whg2.swf',
  'games/worldshardestgame2/worldshardestgame2.html'
  'games/worldshardestgame3/index.html',
  'games/worldshardestgame3/theworldshardestgame3.swf',
  'games/worldshardestgame3/worldshardestgame3.html'
];
